site_name: Awesome Tech
site_url: http://awesome-tech.readthedocs.org
site_description: A curated list of awesome IT projects and resources. Inspired by the awesome list.
site_author: inafev

repo_url: https://github.com/inafev/awesome-tech

theme: readthedocs
extra_css: 
- extra.css
extra_javascript:
- extra.js
site_favicon: images/favicon.ico
markdown_extensions:
- smarty
- sane_lists
pages:
- Home: index.md
- High quality tech resources and search engines: high-quality-tech-resources.md
- Newsfeeds and Twitter resources: twitter.md
- Miscellaneous. IT Blogs, Support: it-blogs.md
- Startups, Multinationals and IT Jobs. In-Demand Skills: startups.md
- Leadership Styles Around the World: leadership_styles_around_world.md
- Barcelona Tech, Startups and Innovation: startups_bcn.md
- Madrid Tech, Startups and Innovation: startups_madrid.md
- Rules for success: rules_for_success.md
- Freelance jobs: freelance_jobs.md
- Motivational videos: motivational_videos.md
- Human Resources: hr.md
- How to Fire and Onboard: howto_fire_onboard.md
- Culture and Collaboration: culture_collaboration.md
- Office Politics: office_politics.md
- Leadership Blogs: leadership.md
- Interview Preparation Guide: interview_preparation_guide.md
- References and online defamation: references.md
- Recursos Humanos: rrhh.md
- Linux: linux.md
- Red Hat: redhat.md
- Red Hat Virtualization: redhatvirt.md
- Red Hat OpenStack: redhat_openstack.md
- Red Hat Cluster: redhatcluster.md
- Linux Commands Examples: linux-commands-examples.md
- Linux Commands Tweets: linux-commands-tweets.md
- Microsoft: microsoft.md
- WebApp, HTTP/2, e-mail, Middleware, JVM, Video: webapp.md
- Caching. CDN Content Delivery Network: caching.md
- Nginx: nginx.md
- F5 Load Balancer: f5lb.md
- Cambios en Java 8: jvm-mem.md
- Security: security.md
- Next Generation Firewalls (NGFW): NGFW.md
- HTTPs and HSTS: https.md
- Security auditing tools: auditing-tools.md
- Security Toolkits and Policies. Penetration Testing: pen_testing.md
- SQL Injection: sql_injection.md
- DevOps and ITIL: devops-itil.md
- Agile planning, CI/CD, Project Management, Scrum, Kanban, Lean: agileplanning.md
- Metrics with APM, Backend Server Monitoring and Alarm System. Grafana, Zabbix: metrics.md
- Elasticsearch, Graylog, Syslog ng: elasticsearch.md
- Continuous Integration Tools. Jenkins, Nexus, Bamboo, Git: jenkins-git.md
- Configuration Management and Orchestration. Microservices: config-mgmt.md
- Ansible: ansible.md
- Puppet: puppet.md
- Chef: chef.md
- Docker: docker.md
- Software Development: sw-devel.md
- Sublime Text Editor: sublime.md
- Java: java.md
- Python: python.md
- Static Site Generators: staticsitegen.md
- QA and Testing: qa.md
- Application Security Testing. OWASP Open Web Application Security Project: app_sec_testing.md
- Testing Tools: qa_tools.md
- Performance Testing Tools. JMeter, Webpagetest, Taurus, Gatling: webperftesting.md
- Scalability and Reliability: scalability.md
- Continuous Integration Tools. Jenkins, Nexus, Bamboo, Git: jenkins-git.md
- Data Science and Big Data: data-science.md
- SQL and Databases: databases.md
- NoSQL and NewSQL. MongoDB : nosql.md
- Anaconda Analytics: anaconda.md
- Big Bang Data: bigbangdata.md
- Networking: networking.md
- Virtual LAN: VLAN.md
- Next Generation Firewalls (NGFW): NGFW.md
- Network Forensics: nw_forensics.md
- Network Performance: nw_performance.md
- CDN Content Delivery Network: cdn.md
- VoIP: voip.md
- Mobile Core Network & Signaling. Diameter: mobilecore.md
- IMS IP Multimedia Subsystem: ims.md
- IPTV Internet Protocol Television: iptv.md
- Servers, Storage and Backup: servers-storage-backup.md
- VMware, VirtualBox: vmware.md
- Cloud: cloud.md
- Amazon Web Services: aws.md
- Desktop Tools and Presentations: desktop-tools.md
- E-Learning: e-learning.md
- Economy: economy.md
- Economy Videos: economy-videos.md
- Economics Films: economics_films.md
- Live News: live-news.md
- World Press Photo: world-press-photo.md
- Quote: mkeiser.md
- About: about.md

markdown_extensions:
    - toc:
        permalink: True
    - admonition:

copyright: Copyright &copy; 2016 <a href="https://twitter.com/RedHatSpain">Red Hat Spain</a>, <a href="http://awesome-tech.readthedocs.org/about/">about</a>.
google_analytics: ['UA-71528100-1', 'awesome tech']