site_name: Awesome Tech
site_url: http://awesome-tech.readthedocs.org
extra_css: 
- extra.css
extra_javascript:
- extra.js
site_favicon: images/favicon.ico
markdown_extensions:
- smarty
- sane_lists
pages:
- Home: index.md
- High quality tech resources and search engines: high-quality-tech-resources.md
- Twitter resources, Newsfeeds: twitter.md
- Miscellaneous. IT Blogs, Support: it-blogs.md
- Startups, Jobs, In-Demand Skills: startups.md
- Human Resources, Interviews, Leadership: hr.md
- Scalability and Reliability, Datacenters: scalability.md
- Linux, Microsoft, VMware: linux-microsoft.md
- Red Hat: redhat.md
- Linux Commands Examples: linux-commands-examples.md
- WebApp, HTTP/2, HTTPs, e-mail, Middleware, JVM, video: webapp.md
- Cambios en Java 8: jvm-mem.md
- Security: security.md
- Configuration Management and Orchestration. Microservices: config-mgmt.md
- Ansible: ansible.md
- Docker: docker.md
- DevOps and ITIL: devops-itil.md
- Continuous Integration Tools: jenkins-git.md
- Metrics: metrics.md
- Elasticsearch: elasticsearch.md
- Software Development: sw-devel.md
- Python: python.md
- Data Science and Big Data: data-science.md
- SQL and Databases: databases.md
- NoSQL and NewSQL: nosql.md
- Networking. Firewalls: networking.md
- Network Forensics: nw_forensics.md
- Servers, Storage and Backup: servers-storage-backup.md
- Cloud: cloud.md
- Desktop Tools and Presentations: desktop-tools.md
- E-Learning: e-learning.md
- Quote: mkeiser.md
- About: about.md
