site_name: Awesome Tech
site_url: http://awesome-tech.readthedocs.org
extra_css: 
- extra.css
extra_javascript:
- extra.js
site_favicon: images/favicon.ico
markdown_extensions:
- smarty
- sane_lists
pages:
- Home: index.md
- High quality tech resources and search engines: high-quality-tech-resources.md
- Newsfeeds and Twitter resources: twitter.md
- Miscellaneous. IT Blogs, Support: it-blogs.md
- Startups, Jobs, In-Demand Skills: startups.md
- Human Resources, Interviews, Leadership: hr.md
- Scalability and Reliability, Datacenters: scalability.md
- Linux: linux.md
- Red Hat: redhat.md
- Linux Commands Examples: linux-commands-examples.md
- Microsoft: microsoft.md
- WebApp, HTTP/2, e-mail, Middleware, JVM, video: webapp.md
- Cambios en Java 8: jvm-mem.md
- Security: security.md
- Next Generation Firewalls (NGFW): NGFW.md
- HTTPs and HSTS: https.md
- Security Toolkits and Policies. Penetration Testing: pen_testing.md
- SQL Injection: sql_injection.md
- Configuration Management and Orchestration. Microservices: config-mgmt.md
- Ansible: ansible.md
- Docker: docker.md
- DevOps and ITIL: devops-itil.md
- Continuous Integration Tools: jenkins-git.md
- Metrics: metrics.md
- Elasticsearch: elasticsearch.md
- Software Development: sw-devel.md
- Sublime Text Editor: sublime.md
- Python: python.md
- Data Science and Big Data: data-science.md
- SQL and Databases: databases.md
- NoSQL and NewSQL: nosql.md
- Anaconda Analytics: anaconda.md
- Big Bang Data: bigbangdata.md
- Networking: networking.md
- Next Generation Firewalls (NGFW): NGFW.md
- Network Forensics: nw_forensics.md
- Servers, Storage and Backup: servers-storage-backup.md
- VMware: vmware.md
- Cloud: cloud.md
- Amazon Web Services: aws.md
- Desktop Tools and Presentations: desktop-tools.md
- E-Learning: e-learning.md
- Quote: mkeiser.md
- About: about.md
