site_name: Awesome Tech
extra_css: [extra.css]
pages:
- Home: index.md
- High quality tech resources and search engines: high-quality-tech-resources.md
- Twitter resources, Newsfeeds: twitter.md
- Miscellaneous. IT Blogs, Support: it-blogs.md
- Startups, Jobs, In-Demand Skills, HR, Interviews: startups.md
- Scalability and Reliability, Datacenters: scalability.md
- Linux, Red Hat, Microsoft, VMware: linux-microsoft.md
- WebApp, Middleware, JVM: webapp.md
- Cambios en Java 8: jvm-mem.md
- Security: security.md
- Configuration Management and Orchestration. Docker: config-mgmt.md
- DevOps and ITIL: devops-itil.md
- Software Development: sw-devel.md
- Data Science and Big Data: data-science.md
- Networking. Firewalls, Network Forensics: networking.md
- Servers, Storage and Backup: servers-storage-backup.md
- Cloud: cloud.md
- Desktop Tools and Presentations: desktop-tools.md
- E-Learning: e-learning.md
- Quote: mkeiser.md
- About: about.md
markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.headeranchor.uslugify
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.nl2br
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.githubemoji
  - pymdownx.tasklist
  - pymdownx.progressbar
  - pymdownx.headeranchor:
      slugify: !!python/name:pymdownx.headeranchor.uslugify
  - pymdownx.arithmatex
  - pymdownx.mark
  - pymdownx.critic